name: flutter_sms_intellect
description: "A modern Flutter plugin to access SMS inbox on Android devices."
version: 0.0.2
homepage: https://github.com/sanjaymadari/flutter_sms_intellect

# Environment constraints for the package
environment:
  sdk: ^3.7.0          # Minimum Dart SDK version required
  flutter: '>=3.0.0'   # Minimum Flutter version required

dependencies:
  flutter:              # Flutter SDK dependency
    sdk: flutter
  plugin_platform_interface: ^2.0.2  # For plugin interface definitions

dev_dependencies:
  flutter_test:         # Testing framework
    sdk: flutter
  flutter_lints: ^5.0.0 # Linting rules for Flutter

# Flutter-specific configuration
flutter:
  # Defines this as a plugin project
  plugin:
    platforms:
      android:
        package: com.sanjaymadari.flutter_sms_intellect  # Android package name
        pluginClass: FlutterSmsIntellectPlugin          # Java/Kotlin plugin class
        kotlinPluginClass: FlutterSmsIntellectPlugin    # Kotlin-specific plugin class

# For generic Dart pubspec information, see:
# https://dart.dev/tools/pub/pubspec
